---
- hosts: 59.110.67.31
  sudo: yes
  vars:
    redis_port: 6379
    redis_password: rgbvr1217
  tasks:
  - name: update apt
    apt: update_cache=yes

  - name: ensure packages installed
    apt: pkg={{ item }} state=latest force=yes
    with_items:
      - make
      - build-essential
      - tcl8.5

  - name: copy latest stable redis
    copy: src=/data/soft/redis-3.2.3.tar.gz dest=/tmp/redis-stable.tar.gz

  - name: untar redis
    command: tar zxf /tmp/redis-stable.tar.gz -C /tmp

  - name: build redis
    command: make -j4 chdir=/tmp/redis-3.2.3/

  - name: create redis group
    group: name=redis state=present system=yes

  - name: create redis user
    user: name=redis group=redis createhome=no shell=/bin/false system=yes state=present

  - name: make sure that /etc/redis exists
    file: path=/etc/redis state=directory mode=0755

  - name: make sure that /var/db/redis exists
    file: path=/var/db/redis state=directory mode=0755 group=redis owner=redis

  - name: make sure redis.log file exists
    copy: src=templates/redis.log dest=/var/log/redis.log owner=redis group=redis mode=0644

  - name: copy redis-server to /etc/init.d
    copy: src=templates/redis-server dest=/etc/init.d/redis-server mode=0755

  - name: copy redis.conf file
    copy: src=templates/redis.conf dest=/etc/redis/redis.conf group=redis owner=redis

  - name: copy custom template
    template: src=templates/redis.local.conf.j2 dest=/etc/redis/redis.local.conf group=redis owner=redis

  - name: installing redis binaries
    command: cp /tmp/redis-3.2.3/src/{{ item }} /usr/bin
    with_items: 
      - redis-server
      - redis-cli
      - redis-check-aof
      - redis-check-rdb
      - redis-sentinel

  - name: cleaning up build files
    command: rm -rf /tmp/{{ item }}
    with_items:
      - redis-3.2.3
      - redis-stable.tar.gz

  - name: ensure redis service is restarted
    service: name=redis-server state=restarted
