---
- hosts: mt-all
  tasks:
  - name: Install zabbix3.0_all.deb package from the internet.
    apt:
      deb: http://repo.zabbix.com/zabbix/3.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.0-1+trusty_all.deb

  - name: update apt
    apt: update_cache=yes force=yes

  - name: Install the package "zabbix-agent"
    apt:
      name: zabbix-agent
      state: present

  - name: copy zabbix_agentd config file
    copy: src=templates/zabbix_agentd.conf  dest=/etc/zabbix/zabbix_agentd.conf
  
  - name: modify config file
    script: /etc/ansible/scripts/modify_zabbix_agentd.sh
