---
- hosts: 10.136.11.159
  vars:
    project_name: ['showserver','showms']
    host_ip: ['status1','status2']
  remote_user: root
  tasks: 
    - name: deploy showms code to remote stat2
      local_action: shell '/opt/deploy/server_ms.sh' {{ project_name[0] }} {{ host_ip[1] }}
      run_once: true

    - name: deploy showms code to remote stat2
      local_action: shell '/opt/deploy/server_ms.sh' {{ project_name[1] }} {{ host_ip[1] }}
      run_once: true
      notify: 
        - stop tomcat2
  handlers:
    - name: stop tomcat2
      service: name=tomcat state=restarted
      delegate_to: 10.136.11.159
