---
- hosts: chat
  vars:
    project_name: ['showserver','showms']
    host_ip: ['status1','status1']
  tasks: 
    - name: update chat1 config
      local_action: shell /bin/sleep 10
      run_once: true

    - name: deploy code to remote chat1
      local_action: shell '/opt/deploy/test.sh' {{ project_name[1] }}
      run_once: true
      notify: 
        - restart chat1

    - name: deploy code to remote chat2
      local_action: shell '/opt/deploy/test.sh' {{ project_name[0] }}
      run_once: true
      notify: 
        - restart chat2

  handlers:
    - name: restart chat1
      shell: supervisorctl status
      delegate_to: 10.254.138.105
    - name: restart chat2
      shell: supervisorctl status
      delegate_to: 10.254.206.137
