#!/bin/bash
SCRIPTDIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

host="user@ip"

while True
do
    lsof -n -i4TCP:8527 | grep LISTEN
    if test $? -eq 0 ; then
        echo "port 8527 is being used by another program"
        sleep 60
    else
        ssh -Nv -D *:8527 -i $SCRIPTDIR/id_rsa -o StrictHostKeyChecking=no $host
        sleep 1
    fi
done

# 使用 id_rsa.pub 做验证
# 需要在远程的机器上 ~/.ssh/authorized_keys 里加入
# mac执行可能出现问题，在mac上新建文件cp保存。

